### ISSUE TITLE
Error using package with Typescript

### ISSUE THREAD

**Issue by sawa-ko** [nfroidure/common-services#12]
I get the following error when using the package with Typescript

```
node_modules/common-services/dist/process.d.ts(1,23): error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
```

**Comment by nfroidure** [comment]
@kaname-png you are probably using the module in the context of a project that uses commonjs modules instead of ES Modules. In the last major version of this module I switched to ES Modules. You can revert to the prior major version or switch you project to ESM. See this link for more information on it: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

If you wish to switch your project feel free to look at this TypeScript config that works well for me: https://github.com/nfroidure/whook/blob/master/packages/whook-example/tsconfig.json
